/* DOCUMENTAÇÃO DE TABELAS DO PROJETO */
/*  Tabela de Crachas X Catracas */

--DROPANDO TABELA
DROP TABLE port_catraca.CRACHAS;

--CRIANDO TABELA
CREATE TABLE port_catraca.CRACHAS(
CD_REGISTRO         INT NOT NULL,
CD_CRACHA           VARCHAR(12) NOT NULL,
TIPO                VARCHAR(2) NOT NULL,
CD_CATRACA          INT NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(12),
HR_CADASTRO         TIMESTAMP,

--PK
CONSTRAINT PK_CD_CRACHA_CATRACA PRIMARY KEY (CD_REGISTRO)
);

--SEQUENCE  
DROP SEQUENCE port_catraca.SEQ_CRACHA_CATRACA;

CREATE SEQUENCE port_catraca.SEQ_CRACHA_CATRACA  
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

--SELECT
SELECT * FROM port_catraca.CRACHAS cra ORDER BY cra.CD_REGISTRO
