/* DOCUMENTAÇÃO DE TABELAS DO PROJETO */
/*  Tabela de Terceiros */

--DROPANDO TABELA
DROP TABLE port_catraca.TERCEIROS;

--CRIANDO TABELA
CREATE TABLE port_catraca.TERCEIROS(
CD_TERCEIRO   INT NOT NULL,
CRACHA        VARCHAR(12),
NM_TERCEIRO   VARCHAR(80) NOT NULL,
DT_NASCIMENTO DATE NOT NULL,
RG            VARCHAR(9) NOT NULL,
CPF           VARCHAR(11) NOT NULL,
CNPJ          VARCHAR(14) NOT NULL,
NM_EMPRESA    VARCHAR(80) NOT NULL,
TP_STATUS     VARCHAR(1) NOT NULL,
DT_INICIO     DATE NOT NULL,
DT_FIM        DATE NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(12),
HR_CADASTRO   TIMESTAMP,
CD_USUARIO_ULT_ALT VARCHAR(12),
HR_ULT_ALT    TIMESTAMP,

--PK
CONSTRAINT PK_CD_TERCEIRO PRIMARY KEY (CD_TERCEIRO)

);

--SEQUENCE
DROP SEQUENCE port_catraca.SEQ_CD_TERCEIRO;
CREATE SEQUENCE port_catraca.SEQ_CD_TERCEIRO  
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

SELECT * FROM port_catraca.TERCEIROS ter ORDER BY ter.CD_TERCEIRO

UPDATE port_catraca.TERCEIROS ter
SET ter.CRACHA = ''
WHERE ter.CRACHA = ''























