/* DOCUMENTA��O DE TABELAS DO PROJETO */
/*  Tabela de TIPOS */

DROP TABLE port_catraca.TIPOS;

CREATE TABLE port_catraca.TIPOS(
  CD_CADASTRO                 INTEGER NOT NULL,
  NM_TIPO                     NVARCHAR2(5) NOT NULL,
  DS_TIPO                     NVARCHAR2(30) NOT NULL,
  
  CONSTRAINT PK_CD_TIPOS PRIMARY KEY (CD_CADASTRO)
);


--SEQUENCE
DROP SEQUENCE port_catraca.SQ_CD_TIPO;

CREATE SEQUENCE port_catraca.SQ_CD_TIPO  
START WITH 1   
INCREMENT BY 1
NOCACHE
NOCYCLE;
