/* DOCUMENTAÇÃO DE TABELAS DO PROJETO */
/*  Tabela de Alunos X Turmas*/

--DROPANDO TABELA
DROP TABLE port_catraca.ALUNOS;

--CRIANDO TABELA
CREATE TABLE port_catraca.ALUNOS(
CD_ALUNO            INT NOT NULL,
CD_TURMA            INT NOT NULL,
NM_ALUNO            VARCHAR(80) NOT NULL,
RG                  VARCHAR(9) NOT NULL,
CD_CRACHA           VARCHAR(12),
SN_ATIVO            VARCHAR(1) NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(12),
HR_CADASTRO         TIMESTAMP,
CD_USUARIO_ULT_ALT  VARCHAR(12),
HR_ULT_ALT          TIMESTAMP,

--PK
CONSTRAINT PK_CD_ALUNO PRIMARY KEY (CD_ALUNO)

);

--SEQUENCE  
DROP SEQUENCE port_catraca.SEQ_CD_ALUNO;

CREATE SEQUENCE port_catraca.SEQ_CD_ALUNO  
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

--SELECT
SELECT * FROM port_catraca.ALUNOS alu ORDER BY alu.CD_TURMA

--INSERT
INSERT INTO port_catraca.ALUNOS
SELECT
port_catraca.SEQ_CD_ALUNO.NEXTVAL AS CD_ALUNO,
'3' AS CD_TURMA,
UPPER('Francisco Monti Marques') AS NM_ALUNO,
'395479769' AS RG,
'A' AS SN_ATIVO,
'000001430000' as CD_USUARIO_CADATRO,
SYSDATE AS HR_CADASTRO,
NULL AS CD_USUARIO_ULT_ALT,
NULL AS HR_ULT_ALT
FROM DUAL;

INSERT INTO port_catraca.ALUNOS
SELECT
port_catraca.SEQ_CD_ALUNO.NEXTVAL AS CD_ALUNO,
'3' AS CD_TURMA,
UPPER('Não Lhe Interessa Seu Palhaço') AS NM_ALUNO,
'123456789' AS RG,
'I' AS SN_ATIVO,
'000001430000' as CD_USUARIO_CADATRO,
SYSDATE AS HR_CADASTRO,
NULL AS CD_USUARIO_ULT_ALT,
NULL AS HR_ULT_ALT
FROM DUAL;

UPDATE port_catraca.ALUNOS alu
SET alu.CD_CRACHA = ''
WHERE alu.CD_CRACHA = ''
