/* DOCUMENTAÇÃO DE TABELAS DO PROJETO */
/*  Tabela de Estagio */

--DROPANDO TABELA
DROP TABLE port_catraca.ESTAGIO;

--CRIANDO TABELA
CREATE TABLE port_catraca.ESTAGIO(
CD_ESTAGIO            INT NOT NULL,
NM_ESTAGIO            VARCHAR(80) NOT NULL,
SN_ATIVO            VARCHAR(1),
HR_INICIO           VARCHAR(5),
HR_FIM              VARCHAR(5),
SN_DOM              VARCHAR(1),
SN_SEG              VARCHAR(1),
SN_TER              VARCHAR(1),
SN_QUA              VARCHAR(1),
SN_QUI              VARCHAR(1),
SN_SEX              VARCHAR(1),
SN_SAB              VARCHAR(1),
CD_USUARIO_CADASTRO VARCHAR(12),
HR_CADASTRO         TIMESTAMP,
CD_USUARIO_ULT_ALT  VARCHAR(12),
HR_ULT_ALT          TIMESTAMP,

--PK
CONSTRAINT PK_CD_ESTAGIO PRIMARY KEY (CD_ESTAGIO)
);

--SEQUENCE  
DROP SEQUENCE port_catraca.SEQ_CD_ESTAGIO;

CREATE SEQUENCE port_catraca.SEQ_CD_ESTAGIO  
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

--SELECT
SELECT * FROM port_catraca.ESTAGIO

DELETE FROM port_catraca.ESTAGIO est WHERE est.ESTAGIO = 8

SELECT est.CD_TURMA, est.NM_TURMA, est.SN_ATIVO
FROM port_catraca.ESTAGIO est

UPDATE port_catraca.ESTAGIO est
SET est.SN_ATIVO = 'I'
WHERE est.CD_ESTAGIO = '5'
